spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3308/luckydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379